## Agenda for Today

1. Numpy
2. Linear Algebra Basics

In [1]:
import numpy as np

In [3]:
vec_list = [1, 2, 3, 4]
vec_list

[1, 2, 3, 4]

In [4]:
vec = np.array(vec_list)

In [5]:
vec

array([1, 2, 3, 4])

In [6]:
type(vec)

numpy.ndarray

In [7]:
type(vec[0])

numpy.int32

In [8]:
mat_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]

In [9]:
mat = np.array(mat_list)

In [10]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [11]:
type(mat)

numpy.ndarray

In [12]:
type(mat[0])

numpy.ndarray

In [13]:
type(mat[0][0])

numpy.int32

In [14]:
mat.shape

(4, 3)

In [24]:
mat_imp_list = [[1, 2, 3], [4, 6], [7, 8, 9], [1, 2, 3]]

In [25]:
mat_imp = np.array(mat_imp_list)

In [26]:
mat_imp

array([list([1, 2, 3]), list([4, 6]), list([7, 8, 9]), list([1, 2, 3])],
      dtype=object)

In [27]:
type(mat_imp[0])

list

In [28]:
print(vec.size, mat.size, mat_imp.size)

4 12 4


In [21]:
del mat_imp_list

In [22]:
print(vec.ndim)
print(mat.ndim)
print(mat_imp.ndim)

1
2


NameError: name 'mat_imp' is not defined

In [23]:
print(vec.size, mat.size, mat_imp.size)

NameError: name 'mat_imp' is not defined

In [31]:
print(vec.shape, mat.shape, mat_imp.shape)

(4,) (4, 3) (4,)


In [32]:
print(len(mat.shape))
print(len(vec.shape))

2
1


In [33]:
print(vec.dtype)
print(mat.dtype)
print(mat_imp.dtype)

int64
int64
object


## Creating data - Systematic approach

In [34]:
np.arange(10)  # <- Creates a array of numbers starting from 0 and ending at 10 - 1 = 9 - With increment of 1 each time

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(20, 25)  # <- Creates a array of numbers starting from 20 and ending at 25 - 1 = 24 - With increment of 1 each time

array([20, 21, 22, 23, 24])

In [36]:
np.arange(11, 32, 4)  # <- Creates a array of numbers starting from 11 and ending at 32 - 1 = 31 - With increment of 4 each time

array([11, 15, 19, 23, 27, 31])

In [37]:
np.arange(11, 31, 4)  # <- Creates a array of numbers starting from 11 and ending at 31 - 1 = 30 - With increment of 4 each time

array([11, 15, 19, 23, 27])

In [38]:
print(np.arange(11, 31, 4), np.arange(11, 31, 4).dtype)
print(np.arange(11, 31., 4), np.arange(11, 31., 4).dtype)

[11 15 19 23 27] int64
[11. 15. 19. 23. 27.] float64


In [39]:
np.array([1, 2, 3, 4.])  # For demonstration of Internal (Inherent) Type Conversion

array([1., 2., 3., 4.])

In [40]:
np.array([1, 2, 3.2, '4'], dtype=np.int64)  # For demonstration of External (Explicit) Type Conversion

array([1, 2, 3, 4])

In [41]:
np.arange(12.6, 10.4, -0.1)  # <- np.arange allows decreasing list of numbers

array([12.6, 12.5, 12.4, 12.3, 12.2, 12.1, 12. , 11.9, 11.8, 11.7, 11.6,
       11.5, 11.4, 11.3, 11.2, 11.1, 11. , 10.9, 10.8, 10.7, 10.6, 10.5])

In [42]:
np.linspace(10, 20, 5)  # <- np.arange(10, 20+1, (20-10)/(5-1))  # Parameter tuning for algorithms

array([10. , 12.5, 15. , 17.5, 20. ])

In [43]:
np.linspace(10, 20, 5, dtype=np.int64)

array([10, 12, 15, 17, 20])

In [44]:
np.zeros((4, 3))  # <- Creates a Array with 4 rows and 3 columns with all values 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.zeros((4))  # <- Creates a Array with 4 elements - all values 0

array([0., 0., 0., 0.])

In [46]:
np.zeros(4)  # <- Creates a Array with 4 elements - all values 0

array([0., 0., 0., 0.])

In [47]:
np.zeros(4, 3)  # <- Fails as shape not provided as a tuple

TypeError: data type not understood

In [48]:
np.ones((4, 3))  # <- 4 rows and 3 columns all ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.zeros_like(mat)  # < Same as np.zeroes(mat.shape, dtype=mat.dtype)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
np.ones_like(mat)  # < Same as np.ones(mat.shape, dtype=mat.dtype)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [51]:
np.identity(4)  # <- Identity Matrix  # I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random Data

1. There is no truely random data. There is no humanly possible way of generating it and no algorithm or computer system that can generate it. *The only known true random system out there is radioactivity*
2. Given a starting point and a logic, psuedo random values may be generated. These systems always give the same result when started from the same starting value **Seed**

## Creating Random Data

In [53]:
np.random.rand(5, 2)  # Random values between 0 and 1

array([[0.58768382, 0.74561932],
       [0.92956949, 0.39388815],
       [0.26572719, 0.71370686],
       [0.09521746, 0.51688856],
       [0.79008437, 0.71834093]])

In [55]:
np.random.randn(5, 5)  # Follows Standard Normal distribution <- Mean = 0 , Standard Deviation = 1

array([[-0.78626758,  0.1102453 , -0.32873567, -0.50865171, -2.83459343],
       [ 0.29174024,  0.56925403,  1.04361509,  0.09472773, -0.06807549],
       [-1.0747372 , -0.45058922,  0.77459572, -1.59609023,  1.13389061],
       [-0.70891301, -1.59607707,  0.69068513, -0.26264516, -0.88351943],
       [ 0.37156406, -0.40001219, -1.25632013,  0.99353844, -0.15682627]])

In [56]:
Vals = np.random.randn(500000)
print(np.mean(Vals), np.std(Vals))

0.0023773246364499887 1.0000674670239114


In [57]:
np.random.randint(10, 50, 12)  # Random Integers -> Min, Max, Number

array([37, 18, 18, 19, 34, 25, 38, 41, 47, 14, 40, 12])

In [58]:
import numpy.random as rnd

In [59]:
rnd.rand(10)

array([0.64138268, 0.61583674, 0.93729975, 0.49095018, 0.73163021,
       0.03957602, 0.17388255, 0.05007819, 0.62513999, 0.99091895])

In [60]:
rnd.randint(10, 20, (2, 5))

array([[12, 17, 11, 10, 16],
       [19, 15, 13, 11, 13]])

In [61]:
?rnd.randint

## Reshaping and Manipulations of Arrays

In [62]:
a = rnd.randint(10, 10000, 1000)

In [63]:
a.shape

(1000,)

In [64]:
a[:50]

array([8881, 7640, 6835, 3116, 4141,  541, 2270, 2002, 3744,  944,  288,
        339, 1942, 6941, 2740, 7270, 3430, 5233, 1290, 7609,  355,  600,
       1594, 9043, 4765, 1555, 4865, 2661, 3524, 8421,  518, 4870, 8003,
       5718, 6971, 5522, 5749,  130, 7414, 1055, 5166, 9673, 5527,  181,
       1293, 9667, 9429, 1871, 6228, 7739])

In [65]:
a.reshape((20, 50)).reshape((100, 10)).flatten()[:100]

array([8881, 7640, 6835, 3116, 4141,  541, 2270, 2002, 3744,  944,  288,
        339, 1942, 6941, 2740, 7270, 3430, 5233, 1290, 7609,  355,  600,
       1594, 9043, 4765, 1555, 4865, 2661, 3524, 8421,  518, 4870, 8003,
       5718, 6971, 5522, 5749,  130, 7414, 1055, 5166, 9673, 5527,  181,
       1293, 9667, 9429, 1871, 6228, 7739, 9826, 2056, 6568, 5977, 2671,
       1507, 8543, 1691, 9866, 3735, 8163, 8198,   95, 8128, 7611, 2146,
       8368,  160, 2418, 5042, 7161, 5198, 2303, 9148, 3410, 6787, 3708,
       5967, 2787, 1684, 3285, 1668, 8075, 3170, 2317,  209, 5947, 9138,
        732, 2465, 9757, 8054, 8519, 9967, 1961, 6527, 4778, 7865, 6324,
       8253])

In [66]:
b = a.reshape((20, 50))
b.sort(axis=1)
b[:2]

array([[ 130,  181,  288,  339,  355,  518,  541,  600,  944, 1055, 1290,
        1293, 1555, 1594, 1871, 1942, 2002, 2270, 2661, 2740, 3116, 3430,
        3524, 3744, 4141, 4765, 4865, 4870, 5166, 5233, 5522, 5527, 5718,
        5749, 6228, 6835, 6941, 6971, 7270, 7414, 7609, 7640, 7739, 8003,
        8421, 8881, 9043, 9429, 9667, 9673],
       [  95,  160,  209,  732, 1507, 1668, 1684, 1691, 1961, 2056, 2146,
        2303, 2317, 2418, 2465, 2671, 2787, 3170, 3285, 3410, 3708, 3735,
        4778, 5042, 5198, 5947, 5967, 5977, 6324, 6527, 6568, 6787, 7161,
        7611, 7865, 8054, 8075, 8128, 8163, 8198, 8253, 8368, 8519, 8543,
        9138, 9148, 9757, 9826, 9866, 9967]])

In [67]:
b = a.reshape((20, 50))
b.sort(axis=0)
b[:2]

array([[  36,   96,  209,  224,  355,  518,  541,  600,  944,  969, 1158,
        1293, 1550, 1576, 1871, 1942, 2002, 2270, 2520, 2740, 2831, 2879,
        3008, 3261, 3542, 3695, 3724, 3973, 4087, 4128, 4210, 4586, 5513,
        5749, 5940, 6027, 6679, 6971, 7270, 7414, 7609, 7640, 7739, 8003,
        8421, 8500, 8596, 9265, 9302, 9477],
       [  80,  160,  212,  339,  584,  664,  889,  924,  969, 1055, 1290,
        1374, 1555, 1594, 2119, 2201, 2364, 2450, 2606, 2802, 3065, 3419,
        3460, 3744, 4141, 4703, 4864, 4870, 5126, 5233, 5362, 5449, 5718,
        5814, 6193, 6612, 6835, 7233, 7436, 7636, 7697, 7806, 8205, 8266,
        8423, 8846, 8899, 9416, 9424, 9586]])

In [68]:
a[:100]

array([  36,   96,  209,  224,  355,  518,  541,  600,  944,  969, 1158,
       1293, 1550, 1576, 1871, 1942, 2002, 2270, 2520, 2740, 2831, 2879,
       3008, 3261, 3542, 3695, 3724, 3973, 4087, 4128, 4210, 4586, 5513,
       5749, 5940, 6027, 6679, 6971, 7270, 7414, 7609, 7640, 7739, 8003,
       8421, 8500, 8596, 9265, 9302, 9477,   80,  160,  212,  339,  584,
        664,  889,  924,  969, 1055, 1290, 1374, 1555, 1594, 2119, 2201,
       2364, 2450, 2606, 2802, 3065, 3419, 3460, 3744, 4141, 4703, 4864,
       4870, 5126, 5233, 5362, 5449, 5718, 5814, 6193, 6612, 6835, 7233,
       7436, 7636, 7697, 7806, 8205, 8266, 8423, 8846, 8899, 9416, 9424,
       9586])

## Look at the data
### Gather Insights and Also learn how to look at slices of data

In [69]:
a.max()

9993

In [70]:
a.min()

36

In [71]:
a.std()

2943.196936797638

In [72]:
x = rnd.randn(10000)
x.argmax()

8320

In [73]:
x.max()

3.6645814867101927

In [74]:
x[x.argmax()]

3.6645814867101927

In [75]:
x.min()

-3.9794926592877733

In [76]:
x[x.argmin()]

-3.9794926592877733

In [90]:
z = rnd.randn(1000).reshape((20, 50))

In [91]:
z[0]

array([ 5.05005574e-01,  4.86885365e-01, -1.21618229e+00, -2.90398268e-01,
       -1.17382099e+00,  2.66344623e-01,  1.29497809e+00, -8.01685752e-01,
        1.04931404e+00, -2.67256659e-01, -1.87081452e-01, -1.17079519e+00,
        3.67738270e-01,  9.78061632e-01, -8.94546563e-01,  9.21072264e-01,
        1.61977461e-01,  9.46652098e-01,  5.40746111e-01,  1.08360622e+00,
       -2.61083876e-01,  4.85870811e-01, -6.64321082e-01, -6.52102576e-01,
       -5.27119423e-01,  1.50777215e+00,  1.02546056e+00,  6.48626534e-01,
       -4.27810561e-01, -1.34901985e+00,  3.25276746e-01,  1.39523979e+00,
        3.67923479e-01,  1.53043103e+00,  6.22210344e-01, -1.95358600e+00,
       -6.09452339e-01,  1.06620314e+00,  1.76451561e+00,  2.93039224e-01,
        5.65669503e-01,  1.26431743e-01,  7.82060966e-01,  3.85984949e-01,
       -7.21667565e-01, -1.56282860e-03,  7.35496093e-01,  1.24738369e+00,
        3.41661873e-01,  4.79343736e-01])

In [92]:
z[0][0]  # Extract row at index 0 (row 1) and then extract value at location 0 (col 1) from this row

0.5050055737352643

In [93]:
z[0, 0]  # Element at Row 1 col 1

0.5050055737352643

In [94]:
z[:5:2, -2:]  # First 5 rows (but only the even locations) and last 2 columns

array([[ 0.34166187,  0.47934374],
       [ 0.45160328, -0.93644899],
       [ 0.0659568 ,  0.16235459]])

# Linear Algebra

In [95]:
mat1 = rnd.randint(1, 10, 9).reshape(3, 3)
mat2 = rnd.randint(1, 10, 9).reshape(3, 3)
mat3 = rnd.randint(1, 10, 3).reshape(1, 3)
mat4 = rnd.randint(1, 10, 3).reshape(3, 1)

In [96]:
mat1

array([[6, 9, 8],
       [5, 6, 9],
       [1, 2, 7]])

In [97]:
mat2

array([[2, 8, 2],
       [4, 6, 7],
       [3, 1, 9]])

In [98]:
mat3

array([[3, 8, 1]])

In [99]:
mat4

array([[4],
       [5],
       [8]])

In [100]:
mat1 + mat2

array([[ 8, 17, 10],
       [ 9, 12, 16],
       [ 4,  3, 16]])

In [101]:
mat1 + mat3

array([[ 9, 17,  9],
       [ 8, 14, 10],
       [ 4, 10,  8]])

In [102]:
mat1 + mat4

array([[10, 13, 12],
       [10, 11, 14],
       [ 9, 10, 15]])

In [103]:
mat1 - mat2

array([[ 4,  1,  6],
       [ 1,  0,  2],
       [-2,  1, -2]])

In [104]:
mat1 / mat2

array([[3.        , 1.125     , 4.        ],
       [1.25      , 1.        , 1.28571429],
       [0.33333333, 2.        , 0.77777778]])

In [105]:
mat1 * mat2

array([[12, 72, 16],
       [20, 36, 63],
       [ 3,  2, 63]])

In [106]:
mat1

array([[6, 9, 8],
       [5, 6, 9],
       [1, 2, 7]])

In [107]:
mat2

array([[2, 8, 2],
       [4, 6, 7],
       [3, 1, 9]])

## Broadcasting in Numpy

Behind the scene, in order to match the shape: Numpy broadcasted the variable *beta* into *gamma* as shown in the below example

In [108]:
alpha = np.array([[1, 2], [3, 4]])  # 2 X 2
beta = np.array([6, 7])  # 1 X 2

In [109]:
alpha + beta

array([[ 7,  9],
       [ 9, 11]])

In [110]:
gamma = np.array([beta, beta])  # 1 X 2 ~~ 2 X 2

In [111]:
gamma  # Broadcasted form of *beta*

array([[6, 7],
       [6, 7]])

In [119]:
alpha + gamma

array([[ 7,  9],
       [ 9, 11]])

### Multiplication

In [116]:
mat1

array([[6, 9, 8],
       [5, 6, 9],
       [1, 2, 7]])

In [117]:
mat2

array([[2, 8, 2],
       [4, 6, 7],
       [3, 1, 9]])

In [112]:
mat1.dot(mat2)

array([[ 72, 110, 147],
       [ 61,  85, 133],
       [ 31,  27,  79]])

### Value at Row 1 Column 1

1. Isolate Row 1 in Matrix 1 and Column 1 in Mat2
2. We do a elementwise multiplication
3. We sum the values up

In [122]:
scores = np.array([[10, 10, 70], [8, 8, 80], [7, 7, 70]])
scores

array([[10, 10, 70],
       [ 8,  8, 80],
       [ 7,  7, 70]])

In [123]:
weights = np.array([0.1, 0.1, 0.8])
weights

array([0.1, 0.1, 0.8])

In [124]:
scores.dot(weights)

array([58. , 65.6, 57.4])

In [125]:
x = np.arange(9).reshape((3, 3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [127]:
x.T  # Transpose <- Flips the matrix about the diagonal == Rows become columns and columns become rows

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [131]:
np.sum(mat1, axis=0)

array([12, 17, 24])

In [132]:
mat1

array([[6, 9, 8],
       [5, 6, 9],
       [1, 2, 7]])

In [133]:
np.sum(mat1, axis=1)

array([23, 20, 10])

### Inner Product

1. Isolate Row 1 of both matrices
2. Perform elementwise multiplication
3. Sum the result

You do not retain the number of columns as all columns are collapsed into one value

In [134]:
?np.inner

In [138]:
mat1

array([[6, 9, 8],
       [5, 6, 9],
       [1, 2, 7]])

In [139]:
mat3

array([[3, 8, 1]])

In [137]:
np.inner(mat1, mat3)  # Inner Product Reduces the dimensionality of the information (Compression)

array([[98],
       [72],
       [26]])

In [148]:
mat3

array([[3, 8, 1]])

In [149]:
mat4

array([[4],
       [5],
       [8]])

In [150]:
np.outer(mat3, mat4)  # Outer Product Increases the dimensionality of the information (Decompression)

array([[12, 15, 24],
       [32, 40, 64],
       [ 4,  5,  8]])

### Matrix misc terminologies

In [151]:
mat1

array([[6, 9, 8],
       [5, 6, 9],
       [1, 2, 7]])

In [153]:
mat1.trace()  # Trace

19

In [154]:
np.linalg.det(mat1)  # Determinant

-57.999999999999986

In [156]:
np.linalg.inv(mat1)  # Inverse of the matrix

array([[-0.4137931 ,  0.81034483, -0.56896552],
       [ 0.44827586, -0.5862069 ,  0.24137931],
       [-0.06896552,  0.05172414,  0.15517241]])

In [159]:
mat1.dot(np.linalg.inv(mat1))  # Matrix * Inverse = Inverse * Matrix = Identity

array([[ 1.00000000e+00,  1.11022302e-16, -4.44089210e-16],
       [ 1.38777878e-17,  1.00000000e+00, -4.44089210e-16],
       [-1.38777878e-17,  8.32667268e-17,  1.00000000e+00]])