## Agenda for Today

1. Numpy
2. Linear Algebra Basics

In [1]:
import numpy as np

In [ ]:
!pip install numpy

In [2]:
vec_list = [1, 2, 3, 4]
vec_list

[1, 2, 3, 4]

In [3]:
vec = np.array(vec_list)

In [4]:
vec

array([1, 2, 3, 4])

In [5]:
type(vec)

numpy.ndarray

In [6]:
type(vec[0])

numpy.int32

In [7]:
mat_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]

In [8]:
mat = np.array(mat_list)

In [9]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [10]:
type(mat)

numpy.ndarray

In [11]:
type(mat[0])

numpy.ndarray

In [12]:
type(mat[0][0])

numpy.int32

In [13]:
mat.shape

(4, 3)

In [14]:
mat_imp_list = [[1, 2, 3], [4, 6], [7, 8, 9], [1, 2, 3]]

In [15]:
mat_imp = np.array(mat_imp_list)

In [16]:
mat_imp

array([list([1, 2, 3]), list([4, 6]), list([7, 8, 9]), list([1, 2, 3])],
      dtype=object)

In [17]:
type(mat_imp[0])

list

In [18]:
print(vec.size, mat.size, mat_imp.size)

4 12 4


In [19]:
del mat_imp_list

In [22]:
print(vec.ndim)
print(mat.ndim)
print(mat_imp.ndim)
#print(mat_imp_list)

1
2
1


NameError: name 'mat_imp_list' is not defined

In [24]:
print(vec.size, mat.size, mat_imp.size)

4 12 4


In [25]:
print(vec.shape, mat.shape, mat_imp.shape)

(4,) (4, 3) (4,)


In [23]:
print(len(mat.shape))
print(len(vec.shape))

2
1


In [26]:
print(vec.dtype)
print(mat.dtype)
print(mat_imp.dtype)

int32
int32
object


## Creating data - Systematic approach

In [27]:
np.arange(10)  # <- Creates a array of numbers starting from 0 and ending at 10 - 1 = 9 - With increment of 1 each time

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(20, 25)  # <- Creates a array of numbers starting from 20 and ending at 25 - 1 = 24 - With increment of 1 each time

array([20, 21, 22, 23, 24])

In [31]:
np.arange(11, 32, 4)  # <- Creates a array of numbers starting from 11 and ending at 32 - 1 = 31 - With increment of 4 each time

array([11, 15, 19, 23, 27, 31])

In [34]:
np.arange(11, 31., 4)  # <- Creates a array of numbers starting from 11 and ending at 31 - 1 = 30 - With increment of 4 each time

array([11., 15., 19., 23., 27.])

In [33]:
print(np.arange(11, 31, 4), np.arange(11, 31, 4).dtype)
print(np.arange(11, 31., 4), np.arange(11, 31., 4).dtype)

[11 15 19 23 27] int32
[11. 15. 19. 23. 27.] float64


In [35]:
np.array([1, 2, 3, 4.])  # For demonstration of Internal (Inherent) Type Conversion

array([1., 2., 3., 4.])

In [46]:
np.array([1, 2, 3.2], dtype=np.int32)  # For demonstration of External (Explicit) Type Conversion

array([1, 2, 3])

In [47]:
np.arange(12.6, 10.4, -0.1)  # <- np.arange allows decreasing list of numbers

array([12.6, 12.5, 12.4, 12.3, 12.2, 12.1, 12. , 11.9, 11.8, 11.7, 11.6,
       11.5, 11.4, 11.3, 11.2, 11.1, 11. , 10.9, 10.8, 10.7, 10.6, 10.5])

In [52]:
np.linspace(10, 20, 5)  # <- np.arange(10, 20+1, (20-10)/(5-1))  # Parameter tuning for algorithms

array([10. , 12.5, 15. , 17.5, 20. ])

In [51]:
np.linspace(10, 20, 5, dtype=np.int64)

array([10, 12, 15, 17, 20], dtype=int64)

In [53]:
np.zeros((4, 3))  # <- Creates a Array with 4 rows and 3 columns with all values 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.zeros((4))  # <- Creates a Array with 4 elements - all values 0

array([0., 0., 0., 0.])

In [56]:
np.zeros(4)  # <- Creates a Array with 4 elements - all values 0

array([0., 0., 0., 0.])

In [55]:
np.zeros((4, 3))  # <- Fails as shape not provided as a tuple

TypeError: data type not understood

In [57]:
np.ones((4, 3))  # <- 4 rows and 3 columns all ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.zeros_like(mat)  # < Same as np.zeroes(mat.shape, dtype=mat.dtype)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
np.ones_like(mat)  # < Same as np.ones(mat.shape, dtype=mat.dtype)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [60]:
np.identity(4)  # <- Identity Matrix  # I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random Data

1. There is no truely random data. There is no humanly possible way of generating it and no algorithm or computer system that can generate it. *The only known true random system out there is radioactivity*
2. Given a starting point and a logic, psuedo random values may be generated. These systems always give the same result when started from the same starting value **Seed**

## Creating Random Data

In [61]:
np.random.rand(5, 2)  # Random values between 0 and 1

array([[0.23456364, 0.91512833],
       [0.37871439, 0.11963159],
       [0.82129926, 0.8129101 ],
       [0.79890414, 0.8280563 ],
       [0.37114002, 0.89102561]])

In [62]:
np.random.randn(5, 5)  # Follows Standard Normal distribution <- Mean = 0 , Standard Deviation = 1

array([[-0.53707377, -0.18229224,  1.90823449,  0.59197975,  2.39424488],
       [-0.63564105, -0.19787122,  0.31177426, -0.92711637,  1.06026608],
       [ 0.67053577,  0.83516924, -0.96086639, -1.18825937,  0.13854555],
       [ 2.98191548,  1.50100507,  0.34518152, -0.4742676 , -0.21309809],
       [-1.73734392, -0.57966588, -0.12713229,  0.09210626, -0.37152449]])

In [63]:
Vals = np.random.randn(500000)
print(np.mean(Vals), np.std(Vals))

-0.0003850570584351262 1.0002361083087883


In [64]:
np.random.randint(10, 50, 12)  # Random Integers -> Min, Max, Number

array([32, 22, 24, 28, 40, 32, 39, 31, 41, 46, 27, 46])

In [65]:
import numpy.random as rnd

In [66]:
rnd.rand(10)

array([0.66438585, 0.67181375, 0.28193257, 0.51668537, 0.66106422,
       0.50709945, 0.71668582, 0.84834711, 0.27455793, 0.52395443])

In [68]:
rnd.randint(10, 20, (5, 2))

array([[11, 15],
       [18, 11],
       [11, 18],
       [10, 12],
       [16, 17]])

In [ ]:
?rnd.randint

## Reshaping and Manipulations of Arrays

In [69]:
a = rnd.randint(10, 10000, 1000)

In [70]:
a.shape

(1000,)

In [71]:
a[:50]

array([9132, 1063, 6166,  490, 4816,  828, 8370, 9815, 1332, 3124, 4852,
       8271, 7109, 8200, 9894, 8713,  357, 7969, 1854, 8111, 1882, 4398,
       8864, 9180, 8896, 8489, 7781,  227, 8221, 7100, 8924, 6314, 6478,
       8996, 3772, 1539, 7568, 5192, 8340, 5291,  149, 5644, 6069, 4681,
       6873, 4822, 4128, 7602, 9714, 1260])

In [74]:
a.reshape((20, 50)).reshape((100, 10)).flatten()[:100]

array([9132, 1063, 6166,  490, 4816,  828, 8370, 9815, 1332, 3124, 4852,
       8271, 7109, 8200, 9894, 8713,  357, 7969, 1854, 8111, 1882, 4398,
       8864, 9180, 8896, 8489, 7781,  227, 8221, 7100, 8924, 6314, 6478,
       8996, 3772, 1539, 7568, 5192, 8340, 5291,  149, 5644, 6069, 4681,
       6873, 4822, 4128, 7602, 9714, 1260, 6179, 2731, 4562, 9716, 3690,
       4526, 6801, 4973, 6434, 5837, 9161,  906, 9126, 5304, 3502, 2224,
       6195, 1840, 3524, 3214, 3361, 9598, 1087, 9477,  462, 9560, 8871,
       3963, 8750, 2901, 6156, 1556, 9046, 8804, 2348, 9852, 6006, 8665,
       4066, 4581, 1294, 3229, 6449, 7507, 1745, 2278, 7017, 8915, 3396,
       6152])

In [88]:
b = a.reshape((20, 50))[:10]

In [89]:
b

array([[  86,  114,  146,  330,  550,  575,  744,  745,  762,  813,  831,
         842,  972, 1613, 1644, 1757, 1918, 2177, 2457, 2753, 2874, 3834,
        3991, 4019, 4124, 4403, 4486, 4499, 4904, 5038, 5089, 5628, 5631,
        5821, 6086, 6184, 6226, 6388, 6563, 6685, 6786, 7099, 7154, 7225,
        7803, 7864, 8242, 8677, 8995, 9183],
       [  87,  141,  184,  368,  562,  604,  756,  795,  882,  961,  983,
        1011, 1303, 1962, 2347, 2378, 2380, 2442, 2951, 2962, 3158, 3895,
        4021, 4225, 4262, 4434, 4599, 4897, 5131, 5168, 5275, 5694, 5837,
        5936, 6131, 6228, 6293, 6815, 6820, 7404, 7535, 7540, 7572, 7710,
        7832, 7930, 8334, 8828, 9213, 9273],
       [  89,  158,  295,  446,  628,  632,  775,  861, 1225, 1481, 1698,
        1780, 1868, 2045, 2406, 2428, 3042, 3161, 3402, 3465, 3808, 3995,
        4087, 4229, 4394, 4746, 4773, 4911, 5149, 5319, 5604, 5758, 5982,
        6114, 6274, 6422, 6790, 7001, 7248, 7416, 7544, 7611, 7667, 8089,
        8151, 8159, 85

In [87]:
b.sort(axis=0)
b[:2]

array([[  86,  114,  146,  330,  550,  575,  744,  745,  762,  813,  831,
         842,  972, 1613, 1644, 1757, 1918, 2177, 2457, 2753, 2874, 3834,
        3991, 4019, 4124, 4403, 4486, 4499, 4904, 5038, 5089, 5628, 5631,
        5821, 6086, 6184, 6226, 6388, 6563, 6685, 6786, 7099, 7154, 7225,
        7803, 7864, 8242, 8677, 8995, 9183],
       [  87,  141,  184,  368,  562,  604,  756,  795,  882,  961,  983,
        1011, 1303, 1962, 2347, 2378, 2380, 2442, 2951, 2962, 3158, 3895,
        4021, 4225, 4262, 4434, 4599, 4897, 5131, 5168, 5275, 5694, 5837,
        5936, 6131, 6228, 6293, 6815, 6820, 7404, 7535, 7540, 7572, 7710,
        7832, 7930, 8334, 8828, 9213, 9273]])

In [76]:
b = a.reshape((20, 50))
b.sort(axis=0)
b[:2]

array([[  86,  114,  146,  330,  550,  575,  744,  745,  762,  813,  831,
         842,  972, 1613, 1644, 1757, 1918, 2177, 2457, 2753, 2874, 3834,
        3991, 4019, 4124, 4403, 4486, 4499, 4904, 5038, 5089, 5628, 5631,
        5821, 6086, 6184, 6226, 6388, 6563, 6685, 6786, 7099, 7154, 7225,
        7803, 7864, 8242, 8677, 8995, 9183],
       [  87,  141,  184,  368,  562,  604,  756,  795,  882,  961,  983,
        1011, 1303, 1962, 2347, 2378, 2380, 2442, 2951, 2962, 3158, 3895,
        4021, 4225, 4262, 4434, 4599, 4897, 5131, 5168, 5275, 5694, 5837,
        5936, 6131, 6228, 6293, 6815, 6820, 7404, 7535, 7540, 7572, 7710,
        7832, 7930, 8334, 8828, 9213, 9273]])

In [81]:
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind='quicksort', order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be used, in the order in which
        they come up in the dtype, to break ties.
    
    Returns
    -------
    sorted_array : ndarray
        Array of the same type and shape as `a`.
    
    S

## Look at the data
### Gather Insights and Also learn how to look at slices of data

In [90]:
a.max()

9987

In [91]:
a.min()

86

In [92]:
a.std()

2848.3957346954094

In [95]:
a.argmin()

0

In [96]:
a[0]

86

In [ ]:
x = rnd.randn(10000)
x.argmax()

In [ ]:
x.max()

In [ ]:
x[x.argmax()]

In [ ]:
x.min()

In [ ]:
x[x.argmin()]

In [ ]:
z = rnd.randn(1000).reshape((20, 50))

In [ ]:
z[0]

In [ ]:
z[0][0]  # Extract row at index 0 (row 1) and then extract value at location 0 (col 1) from this row

In [ ]:
z[0, 0]  # Element at Row 1 col 1

In [ ]:
z[:5:2, -2:]  # First 5 rows (but only the even locations) and last 2 columns

# Linear Algebra

In [97]:
mat1 = rnd.randint(1, 10, 9).reshape(3, 3)
mat2 = rnd.randint(1, 10, 9).reshape(3, 3)
mat3 = rnd.randint(1, 10, 3).reshape(1, 3)
mat4 = rnd.randint(1, 10, 3).reshape(3, 1)

In [99]:
mat2

array([[9, 3, 7],
       [5, 6, 7],
       [4, 4, 6]])

In [100]:
mat3

array([[3, 6, 1]])

In [98]:
mat1

array([[8, 8, 1],
       [7, 4, 8],
       [5, 8, 9]])

In [101]:
mat4

array([[9],
       [5],
       [8]])

In [102]:
mat1 + mat2

array([[17, 11,  8],
       [12, 10, 15],
       [ 9, 12, 15]])

In [103]:
mat1 + mat3

array([[11, 14,  2],
       [10, 10,  9],
       [ 8, 14, 10]])

In [104]:
mat1 + mat4

array([[17, 17, 10],
       [12,  9, 13],
       [13, 16, 17]])

In [105]:
mat1 - mat2

array([[-1,  5, -6],
       [ 2, -2,  1],
       [ 1,  4,  3]])

In [106]:
mat1 / mat2

array([[0.88888889, 2.66666667, 0.14285714],
       [1.4       , 0.66666667, 1.14285714],
       [1.25      , 2.        , 1.5       ]])

In [107]:
mat1 * mat2

array([[72, 24,  7],
       [35, 24, 56],
       [20, 32, 54]])

In [108]:
mat1

array([[8, 8, 1],
       [7, 4, 8],
       [5, 8, 9]])

In [109]:
mat2

array([[9, 3, 7],
       [5, 6, 7],
       [4, 4, 6]])

## Broadcasting in Numpy

Behind the scene, in order to match the shape: Numpy broadcasted the variable *beta* into *gamma* as shown in the below example

In [ ]:
alpha = np.array([[1, 2], [3, 4]])  # 2 X 2
beta = np.array([6, 7])  # 1 X 2

In [ ]:
alpha + beta

In [ ]:
gamma = np.array([beta, beta])  # 1 X 2 ~~ 2 X 2

In [ ]:
gamma  # Broadcasted form of *beta*

In [ ]:
alpha + gamma

### Multiplication

In [110]:
mat1

array([[8, 8, 1],
       [7, 4, 8],
       [5, 8, 9]])

In [111]:
mat2

array([[9, 3, 7],
       [5, 6, 7],
       [4, 4, 6]])

In [112]:
mat1.dot(mat2)

array([[116,  76, 118],
       [115,  77, 125],
       [121,  99, 145]])

### Value at Row 1 Column 1

1. Isolate Row 1 in Matrix 1 and Column 1 in Mat2
2. We do a elementwise multiplication
3. We sum the values up

In [119]:
scores = np.array([[10, 10, 70], [8, 8, 80], [7, 7, 70]])
scores

array([[10, 10, 70],
       [ 8,  8, 80],
       [ 7,  7, 70]])

In [117]:
weights = np.array([0.1, 0.1, 0.8])
weights

array([0.1, 0.1, 0.8])

In [118]:
scores.dot(weights)

array([58. , 65.6, 57.4])

In [120]:
weights.dot(scores)

array([ 7.4,  7.4, 71. ])

In [ ]:
x = np.arange(9).reshape((3, 3))
x

In [ ]:
x.T  # Transpose <- Flips the matrix about the diagonal == Rows become columns and columns become rows

In [ ]:
np.sum(mat1, axis=0)

In [ ]:
mat1

In [ ]:
np.sum(mat1, axis=1)

### Inner Product

1. Isolate Row 1 of both matrices
2. Perform elementwise multiplication
3. Sum the result

You do not retain the number of columns as all columns are collapsed into one value

In [ ]:
?np.inner

In [113]:
mat1

array([[8, 8, 1],
       [7, 4, 8],
       [5, 8, 9]])

In [114]:
mat3

array([[3, 6, 1]])

In [115]:
np.inner(mat1, mat3)  # Inner Product Reduces the dimensionality of the information (Compression)

array([[73],
       [53],
       [72]])

### Matrix misc terminologies

In [ ]:
mat1

In [ ]:
mat1.trace()  # Trace

In [ ]:
np.linalg.det(mat1)  # Determinant

In [ ]:
np.linalg.inv(mat1)  # Inverse of the matrix

In [ ]:
mat1.dot(np.linalg.inv(mat1))  # Matrix * Inverse = Inverse * Matrix = Identity